/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 22 16:12:34 GMT 2021
 */

package org.jtetris.models.elements;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jtetris.models.elements.Block;
import org.jtetris.models.elements.Grid;
import org.junit.runner.RunWith;

 
public class Block_ESTest{

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Block block0 = new Block(22);
      // Undeclared exception!
      try { 
        block0.beAddedToScreen();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 10
         //
         verifyException("org.jtetris.models.elements.Block", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Block block0 = new Block(1);
      block0.x_position = 20;
      block0.moveLeft();
      assertEquals(19, block0.x_position);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Block block0 = new Block(0);
      block0.x_position = (-1);
      // Undeclared exception!
      try { 
        block0.moveLeft();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Block block0 = new Block(0);
      block0.x_position = 10;
      // Undeclared exception!
      try { 
        block0.moveRight();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Block block0 = new Block(2644);
      // Undeclared exception!
      block0.moveRight();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Block block0 = new Block(1163);
      block0.occupied = null;
      // Undeclared exception!
      try { 
        block0.moveRight();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Block block0 = new Block(755);
      // Undeclared exception!
      block0.moveLeft();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Block block0 = new Block(0);
      block0.occupied = null;
      // Undeclared exception!
      try { 
        block0.moveLeft();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Block block0 = new Block(637);
      // Undeclared exception!
      block0.moveDown();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Block block0 = new Block(1342);
      block0.occupied = block0.occupied;
      block0.occupied = null;
      // Undeclared exception!
      try { 
        block0.moveDown();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jtetris.models.elements.Grid", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Block block0 = new Block(0);
      block0.y_position = 0;
      // Undeclared exception!
      try { 
        block0.moveDown();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Block block0 = new Block(10);
      block0.occupied = null;
      // Undeclared exception!
      try { 
        block0.beAddedToScreen();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jtetris.models.elements.Block", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Block block0 = null;
      try {
        block0 = new Block((-2854));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jtetris.models.elements.Grid", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Block block0 = new Block(1);
      Grid grid0 = block0.beAddedToScreen();
      assertEquals(10, grid0.width);
      assertEquals(0, block0.x_position);
      assertEquals(21, block0.y_position);
      assertEquals(22, grid0.height);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Block block0 = new Block(1);
      assertEquals(21, block0.y_position);
      
      block0.y_position = 1;
      boolean[][] booleanArray0 = new boolean[1][4];
      boolean[] booleanArray1 = new boolean[7];
      booleanArray1[0] = true;
      block0.y_position = 0;
      booleanArray0[0] = booleanArray1;
      block0.occupied = booleanArray0;
      block0.moveDown();
      assertEquals(0, block0.y_position);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Block block0 = new Block(1);
      block0.moveDown();
      assertEquals(20, block0.y_position);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Block block0 = new Block(1);
      boolean[][] booleanArray0 = new boolean[1][4];
      boolean[] booleanArray1 = new boolean[7];
      booleanArray1[0] = true;
      booleanArray0[0] = booleanArray1;
      block0.occupied = booleanArray0;
      block0.moveLeft();
      assertEquals(0, block0.x_position);
      assertEquals(21, block0.y_position);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Block block0 = new Block(1);
      boolean[][] booleanArray0 = new boolean[1][3];
      boolean[] booleanArray1 = new boolean[3];
      booleanArray1[0] = true;
      booleanArray0[0] = booleanArray1;
      block0.occupied = booleanArray0;
      block0.x_position = 13;
      block0.moveRight();
      assertEquals(13, block0.x_position);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Block block0 = new Block(1);
      block0.moveRight();
      assertEquals(1, block0.x_position);
      
      block0.moveLeft();
      assertEquals(0, block0.x_position);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Block block0 = new Block(0);
      block0.rotate();
      assertEquals(0, block0.x_position);
      assertEquals(22, block0.y_position);
  }
}
