/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 08 15:26:19 GMT 2021
 */

package org.ta4j.core.indicators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.BarSeries;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.Indicator;
import org.ta4j.core.indicators.RWIHighIndicator;
import org.ta4j.core.num.Num;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RWIHighIndicator_ESTest extends RWIHighIndicator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator(baseBarSeries0, 3);
      // Undeclared exception!
      try { 
        Indicator.toDouble(rWIHighIndicator0, 3, 3);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator(baseBarSeries0, 5);
      Num num0 = rWIHighIndicator0.calculate((-712));
      assertEquals("NaN", num0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator(baseBarSeries0, 5);
      // Undeclared exception!
      try { 
        rWIHighIndicator0.calculate(5);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator(baseBarSeries0, 5);
      String string0 = rWIHighIndicator0.toString();
      assertEquals("RWIHighIndicator barCount: 5", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator((BarSeries) null, 0);
      // Undeclared exception!
      try { 
        rWIHighIndicator0.calculate(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.RWIHighIndicator", e);
      }
  }
}
