/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Mar 08 15:26:19 GMT 2021
 */

package org.ta4j.core.indicators;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class RWIHighIndicator_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.ta4j.core.indicators.RWIHighIndicator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\mgh\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "Z:\\case-study-oo-coverage-and-mutants\\ta4j-RWIHighIndicator"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\mgh"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "mgh"); 
    java.lang.System.setProperty("user.timezone", "Asia/Tehran"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RWIHighIndicator_ESTest_scaffolding.class.getClassLoader() ,
      "org.ta4j.core.indicators.ChopIndicator",
      "org.ta4j.core.indicators.RWIHighIndicator",
      "org.ta4j.core.indicators.MMAIndicator",
      "org.ta4j.core.BaseTradingRecord",
      "org.ta4j.core.indicators.FisherIndicator",
      "org.ta4j.core.indicators.AwesomeOscillatorIndicator",
      "org.ta4j.core.ConvertibleBaseBarBuilder",
      "org.ta4j.core.cost.CostModel",
      "org.ta4j.core.indicators.helpers.HighPriceIndicator",
      "org.ta4j.core.indicators.ZLEMAIndicator",
      "org.ta4j.core.indicators.ParabolicSarIndicator",
      "org.ta4j.core.cost.ZeroCostModel",
      "org.ta4j.core.indicators.MassIndexIndicator",
      "org.ta4j.core.indicators.EMAIndicator",
      "org.ta4j.core.num.PrecisionNum",
      "org.ta4j.core.indicators.helpers.ClosePriceIndicator",
      "org.ta4j.core.indicators.WilliamsRIndicator",
      "org.ta4j.core.indicators.CoppockCurveIndicator",
      "org.ta4j.core.Order$OrderType",
      "org.ta4j.core.analysis.CashFlow",
      "org.ta4j.core.indicators.RecursiveCachedIndicator",
      "org.ta4j.core.indicators.AroonOscillatorIndicator",
      "org.ta4j.core.indicators.AroonUpIndicator",
      "org.ta4j.core.indicators.helpers.GainIndicator",
      "org.ta4j.core.indicators.helpers.SumIndicator",
      "org.ta4j.core.indicators.helpers.LossIndicator",
      "org.ta4j.core.indicators.StochasticRSIIndicator",
      "org.ta4j.core.indicators.helpers.TRIndicator",
      "org.ta4j.core.cost.LinearTransactionCostModel",
      "org.ta4j.core.indicators.AroonDownIndicator",
      "org.ta4j.core.indicators.MACDIndicator",
      "org.ta4j.core.indicators.helpers.MedianPriceIndicator",
      "org.ta4j.core.indicators.DoubleEMAIndicator",
      "org.ta4j.core.indicators.RAVIIndicator",
      "org.ta4j.core.Trade",
      "org.ta4j.core.indicators.helpers.HighestValueIndicator",
      "org.ta4j.core.indicators.SMAIndicator",
      "org.ta4j.core.indicators.AbstractIndicator",
      "org.ta4j.core.indicators.ROCIndicator",
      "org.ta4j.core.indicators.CachedIndicator",
      "org.ta4j.core.indicators.helpers.LowPriceIndicator",
      "org.ta4j.core.indicators.PPOIndicator",
      "org.ta4j.core.num.NaN",
      "org.ta4j.core.indicators.RSIIndicator",
      "org.ta4j.core.indicators.ChandelierExitShortIndicator",
      "org.ta4j.core.indicators.AbstractEMAIndicator",
      "org.ta4j.core.cost.LinearBorrowingCostModel",
      "org.ta4j.core.BaseBarSeries",
      "org.ta4j.core.indicators.helpers.DifferenceIndicator",
      "org.ta4j.core.num.Num",
      "org.ta4j.core.Order",
      "org.ta4j.core.indicators.StochasticOscillatorKIndicator",
      "org.ta4j.core.Indicator",
      "org.ta4j.core.analysis.Returns",
      "org.ta4j.core.num.DoubleNum",
      "org.ta4j.core.indicators.helpers.PriceIndicator",
      "org.ta4j.core.indicators.StochasticOscillatorDIndicator",
      "org.ta4j.core.indicators.UlcerIndexIndicator",
      "org.ta4j.core.BarSeries",
      "org.ta4j.core.indicators.CMOIndicator",
      "org.ta4j.core.indicators.DPOIndicator",
      "org.ta4j.core.BaseBarBuilder",
      "org.ta4j.core.indicators.TripleEMAIndicator",
      "org.ta4j.core.Bar",
      "org.ta4j.core.indicators.RWILowIndicator",
      "org.ta4j.core.indicators.ATRIndicator",
      "org.ta4j.core.indicators.KAMAIndicator",
      "org.ta4j.core.Order$OrderType$2",
      "org.ta4j.core.indicators.helpers.LowestValueIndicator",
      "org.ta4j.core.Order$OrderType$1",
      "org.ta4j.core.indicators.LWMAIndicator",
      "org.ta4j.core.indicators.AccelerationDecelerationIndicator",
      "org.ta4j.core.BaseBar",
      "org.ta4j.core.indicators.CCIIndicator",
      "org.ta4j.core.indicators.HMAIndicator",
      "org.ta4j.core.TradingRecord",
      "org.ta4j.core.indicators.helpers.MultiplierIndicator",
      "org.ta4j.core.indicators.WMAIndicator",
      "org.ta4j.core.indicators.ChandelierExitLongIndicator"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RWIHighIndicator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.ta4j.core.indicators.AbstractIndicator",
      "org.ta4j.core.indicators.CachedIndicator",
      "org.ta4j.core.indicators.RWIHighIndicator",
      "org.ta4j.core.num.NaN",
      "org.ta4j.core.BaseBarSeries",
      "org.ta4j.core.num.DoubleNum",
      "org.ta4j.core.num.PrecisionNum",
      "org.ta4j.core.indicators.ChopIndicator",
      "org.ta4j.core.indicators.ATRIndicator",
      "org.ta4j.core.indicators.RecursiveCachedIndicator",
      "org.ta4j.core.indicators.AbstractEMAIndicator",
      "org.ta4j.core.indicators.MMAIndicator",
      "org.ta4j.core.indicators.helpers.TRIndicator",
      "org.ta4j.core.cost.LinearTransactionCostModel",
      "org.ta4j.core.indicators.WMAIndicator",
      "org.ta4j.core.indicators.FisherIndicator",
      "org.ta4j.core.indicators.helpers.MedianPriceIndicator",
      "org.ta4j.core.BaseBar",
      "org.ta4j.core.Trade",
      "org.ta4j.core.cost.ZeroCostModel",
      "org.ta4j.core.indicators.AccelerationDecelerationIndicator",
      "org.ta4j.core.indicators.AwesomeOscillatorIndicator",
      "org.ta4j.core.indicators.SMAIndicator",
      "org.ta4j.core.analysis.Returns",
      "org.ta4j.core.indicators.CCIIndicator",
      "org.ta4j.core.indicators.DoubleEMAIndicator",
      "org.ta4j.core.indicators.EMAIndicator",
      "org.ta4j.core.indicators.RAVIIndicator",
      "org.ta4j.core.indicators.MassIndexIndicator",
      "org.ta4j.core.indicators.helpers.DifferenceIndicator",
      "org.ta4j.core.indicators.helpers.PriceIndicator",
      "org.ta4j.core.indicators.helpers.HighPriceIndicator",
      "org.ta4j.core.indicators.helpers.LowPriceIndicator",
      "org.ta4j.core.indicators.AroonOscillatorIndicator",
      "org.ta4j.core.indicators.AroonDownIndicator",
      "org.ta4j.core.Order",
      "org.ta4j.core.indicators.RWILowIndicator",
      "org.ta4j.core.indicators.helpers.ClosePriceIndicator",
      "org.ta4j.core.indicators.WilliamsRIndicator",
      "org.ta4j.core.indicators.StochasticRSIIndicator",
      "org.ta4j.core.indicators.RSIIndicator",
      "org.ta4j.core.indicators.helpers.GainIndicator",
      "org.ta4j.core.BaseTradingRecord",
      "org.ta4j.core.indicators.ChandelierExitLongIndicator",
      "org.ta4j.core.indicators.helpers.HighestValueIndicator",
      "org.ta4j.core.indicators.DPOIndicator",
      "org.ta4j.core.indicators.StochasticOscillatorDIndicator",
      "org.ta4j.core.indicators.ROCIndicator",
      "org.ta4j.core.indicators.CMOIndicator",
      "org.ta4j.core.indicators.helpers.LossIndicator",
      "org.ta4j.core.indicators.StochasticOscillatorKIndicator",
      "org.ta4j.core.analysis.CashFlow",
      "org.ta4j.core.cost.LinearBorrowingCostModel",
      "org.ta4j.core.indicators.AroonUpIndicator",
      "org.ta4j.core.indicators.ChandelierExitShortIndicator",
      "org.ta4j.core.indicators.helpers.LowestValueIndicator",
      "org.ta4j.core.indicators.MACDIndicator",
      "org.ta4j.core.indicators.TripleEMAIndicator",
      "org.ta4j.core.indicators.PPOIndicator",
      "org.ta4j.core.indicators.HMAIndicator",
      "org.ta4j.core.indicators.helpers.MultiplierIndicator",
      "org.ta4j.core.indicators.CoppockCurveIndicator",
      "org.ta4j.core.indicators.helpers.SumIndicator",
      "org.ta4j.core.indicators.ZLEMAIndicator",
      "org.ta4j.core.indicators.UlcerIndexIndicator",
      "org.ta4j.core.indicators.KAMAIndicator",
      "org.ta4j.core.indicators.ParabolicSarIndicator",
      "org.ta4j.core.indicators.LWMAIndicator"
    );
  }
}
