/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 06 12:59:14 GMT 2021
 */

package org.ta4j.core.indicators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.BarSeries;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.Indicator;
import org.ta4j.core.indicators.SMAIndicator;
import org.ta4j.core.indicators.StochasticOscillatorKIndicator;
import org.ta4j.core.indicators.helpers.HighPriceIndicator;
import org.ta4j.core.num.Num;

 
public class SMAIndicator_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      HighPriceIndicator highPriceIndicator0 = new HighPriceIndicator(baseBarSeries0);
      SMAIndicator sMAIndicator0 = new SMAIndicator(highPriceIndicator0, (-2));
      // Undeclared exception!
      try { 
        sMAIndicator0.calculate((-2));
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StochasticOscillatorKIndicator stochasticOscillatorKIndicator0 = new StochasticOscillatorKIndicator((BarSeries) null, 0);
      SMAIndicator sMAIndicator0 = new SMAIndicator(stochasticOscillatorKIndicator0, 0);
      // Undeclared exception!
      try { 
        sMAIndicator0.calculate((-941));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.AbstractIndicator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SMAIndicator sMAIndicator0 = null;
      try {
        sMAIndicator0 = new SMAIndicator((Indicator<Num>) null, 14);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.CachedIndicator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      HighPriceIndicator highPriceIndicator0 = new HighPriceIndicator(baseBarSeries0);
      SMAIndicator sMAIndicator0 = new SMAIndicator(highPriceIndicator0, (-2));
      String string0 = sMAIndicator0.toString();
      assertEquals("SMAIndicator barCount: -2", string0);
  }
}
