/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 19 16:41:41 GMT 2021
 */

package org.apache.commons.validator.routines;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.text.DateFormat;
import java.util.Locale;
import org.apache.commons.validator.routines.LongValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.text.MockSimpleDateFormat;
import org.junit.runner.RunWith;

 
public class LongValidator_ESTest{

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long(0);
      boolean boolean0 = longValidator0.maxValue(long0, 0L);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Long long0 = new Long(0L);
      boolean boolean0 = longValidator0.isInRange(long0, 0L, 0L);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Locale locale0 = Locale.JAPANESE;
      Long long0 = longValidator0.validate("0", locale0);
      assertEquals(0L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Locale locale0 = Locale.CANADA_FRENCH;
      Long long0 = longValidator0.validate("8", locale0);
      assertEquals(8L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Locale locale0 = Locale.JAPANESE;
      Long long0 = longValidator0.validate("-39", locale0);
      assertEquals((-39L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Locale locale0 = Locale.forLanguageTag("tgjsW8jw.=5FsODs");
      Long long0 = longValidator0.validate("-3,321", "", locale0);
      assertEquals((-3321L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Locale locale0 = Locale.forLanguageTag("U|0A5]");
      Long long0 = longValidator0.validate("U|0A5]", "U|0A5]", locale0);
      assertEquals(0L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Locale locale0 = Locale.ENGLISH;
      LongValidator longValidator0 = new LongValidator(false, (-2771));
      Long long0 = longValidator0.validate("93Mc", "", locale0);
      assertEquals(93L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = longValidator0.validate("3,490", "", (Locale) null);
      assertEquals(3490L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator(true, (-2863));
      Long long0 = longValidator0.validate("-1,756", "");
      assertEquals((-1756L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Long long0 = longValidator0.validate("g680IN", "g680IN");
      assertEquals(0L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Long long0 = longValidator0.validate("373", "");
      assertEquals(373L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator(false, 2962);
      Long long0 = longValidator0.validate("7tk");
      assertEquals(7L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Long long0 = longValidator0.validate("0");
      assertEquals(0L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Long long0 = longValidator0.validate("-3,321");
      assertEquals((-3321L), (long)long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long(0);
      boolean boolean0 = longValidator0.minValue(long0, (long) 1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long(799L);
      boolean boolean0 = longValidator0.maxValue(long0, (-148L));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long((-1L));
      boolean boolean0 = longValidator0.isInRange(long0, (-1L), 0L);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Locale locale0 = Locale.ROOT;
      // Undeclared exception!
      try { 
        longValidator0.validate("org.apache.commons.validator.routines.AbstractNumberValidator", "org.apache.commons.validator.routines.AbstractNumberValidator", locale0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Multiple decimal separators in pattern \"org.apache.commons.validator.routines.AbstractNumberValidator\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      // Undeclared exception!
      try { 
        longValidator0.validate("org.apache.commons.validator.routines.LongValidator", "org.apache.commons.validator.routines.LongValidator");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Multiple decimal separators in pattern \"org.apache.commons.validator.routines.LongValidator\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator(false, 100);
      // Undeclared exception!
      try { 
        longValidator0.minValue((Long) null, (-2169L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.LongValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      // Undeclared exception!
      try { 
        longValidator0.maxValue((Long) null, 583L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.LongValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      // Undeclared exception!
      try { 
        longValidator0.isInRange((Long) null, 538L, 1L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.LongValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      boolean boolean0 = longValidator0.maxValue(0L, 44L);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator(false, 678);
      boolean boolean0 = longValidator0.minValue((long) 678, (-2978L));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      boolean boolean0 = longValidator0.isInRange(538L, 1L, 1L);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator(false, 678);
      boolean boolean0 = longValidator0.isInRange((-451L), 0L, (-451L));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long(0);
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat();
      Object object0 = longValidator0.processParsedValue(long0, mockSimpleDateFormat0);
      assertEquals(0L, object0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      DateFormat dateFormat0 = DateFormat.getDateInstance();
      Object object0 = longValidator0.processParsedValue("q", dateFormat0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      boolean boolean0 = longValidator0.maxValue((long) 0, (-26L));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      boolean boolean0 = longValidator0.minValue(0L, 1L);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      boolean boolean0 = longValidator0.isInRange((long) 0, (long) 0, (long) 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long(0);
      boolean boolean0 = longValidator0.isInRange(long0, (-45L), (-45L));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = new Long(0);
      boolean boolean0 = longValidator0.minValue(long0, (long) 0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = longValidator0.validate("q", "q");
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Long long0 = longValidator0.validate("q");
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LongValidator longValidator0 = new LongValidator();
      Locale locale0 = Locale.KOREAN;
      Long long0 = longValidator0.validate((String) null, locale0);
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LongValidator longValidator0 = LongValidator.getInstance();
      Locale locale0 = Locale.CANADA;
      Long long0 = longValidator0.validate("ZX|R\"{", "ZX|R\"{", locale0);
      assertNull(long0);
  }
}
