/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 22 15:38:07 GMT 2021
 */

package org.jtetris.models.elements;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jtetris.models.elements.Rectangle;
import org.junit.runner.RunWith;

 
public class Rectangle_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Rectangle rectangle0 = new Rectangle();
      rectangle0.occupied = null;
      // Undeclared exception!
      try { 
        rectangle0.rotate();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jtetris.models.elements.Rectangle", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Rectangle rectangle0 = new Rectangle();
      rectangle0.rotate();
      rectangle0.rotate();
      assertEquals(4, rectangle0.height);
  }
}
