/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 16:49:10 GMT 2021
 */

package org.jtetris.models.elements;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jtetris.models.elements.Square;
import org.junit.runner.RunWith;

 
public class Square_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Square square0 = new Square();
      assertEquals(2, square0.height);
  }
}
