/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 06 13:55:49 GMT 2021
 */

package org.ta4j.core.indicators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.Bar;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.Indicator;
import org.ta4j.core.indicators.MMAIndicator;
import org.ta4j.core.indicators.helpers.ClosePriceIndicator;
import org.ta4j.core.num.Num;

 
public class MMAIndicator_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Bar> linkedList0 = new LinkedList<Bar>();
      BaseBarSeries baseBarSeries0 = new BaseBarSeries(linkedList0);
      ClosePriceIndicator closePriceIndicator0 = new ClosePriceIndicator(baseBarSeries0);
      MMAIndicator mMAIndicator0 = null;
      try {
        mMAIndicator0 = new MMAIndicator(closePriceIndicator0, 10);
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MMAIndicator mMAIndicator0 = null;
      try {
        mMAIndicator0 = new MMAIndicator((Indicator<Num>) null, 2222);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.RecursiveCachedIndicator", e);
      }
  }
}
