/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 22 15:45:54 GMT 2021
 */

package org.jtetris.models.elements;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jtetris.models.elements.ReverseL;
import org.junit.runner.RunWith;

 
public class ReverseL_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReverseL reverseL0 = new ReverseL();
      assertEquals(0, reverseL0.x_position);
  }
}
