/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 06 12:40:31 GMT 2021
 */

package org.ta4j.core.indicators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.Indicator;
import org.ta4j.core.indicators.DPOIndicator;
import org.ta4j.core.indicators.RSIIndicator;
import org.ta4j.core.num.Num;

 
public class RSIIndicator_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      DPOIndicator dPOIndicator0 = new DPOIndicator(baseBarSeries0, 4);
      RSIIndicator rSIIndicator0 = null;
      try {
        rSIIndicator0 = new RSIIndicator(dPOIndicator0, 733);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RSIIndicator rSIIndicator0 = null;
      try {
        rSIIndicator0 = new RSIIndicator((Indicator<Num>) null, (-666));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.CachedIndicator", e);
      }
  }
}
