/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 22 15:54:09 GMT 2021
 */

package org.jtetris.models.elements;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jtetris.models.elements.S;
import org.junit.runner.RunWith;

 
public class S_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      S s0 = new S();
      assertEquals(3, s0.width);
  }
}
