/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 06 11:55:22 GMT 2021
 */

package org.ta4j.core.indicators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.Bar;
import org.ta4j.core.BarSeries;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.Indicator;
import org.ta4j.core.indicators.DPOIndicator;
import org.ta4j.core.indicators.RWIHighIndicator;
import org.ta4j.core.indicators.RWILowIndicator;
import org.ta4j.core.num.Num;

public class DPOIndicator_ESTest {

/* removed manually becuase of fauilure when running with general Junit runner
  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator(baseBarSeries0, 310);
      DPOIndicator dPOIndicator0 = new DPOIndicator(rWIHighIndicator0, (-515));
      // Undeclared exception!
      try { 
        dPOIndicator0.calculate((-515));
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }
*/

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DPOIndicator dPOIndicator0 = new DPOIndicator((BarSeries) null, 0);
      // Undeclared exception!
      try { 
        dPOIndicator0.calculate((-352));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.helpers.PriceIndicator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Bar> linkedList0 = new LinkedList<Bar>();
      BaseBarSeries baseBarSeries0 = new BaseBarSeries(linkedList0);
      RWILowIndicator rWILowIndicator0 = new RWILowIndicator(baseBarSeries0, 14);
      DPOIndicator dPOIndicator0 = new DPOIndicator(rWILowIndicator0, (-25));
      rWILowIndicator0.highestResultIndex = 125;
      // Undeclared exception!
      try { 
        dPOIndicator0.calculate((-25));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      DPOIndicator dPOIndicator0 = new DPOIndicator(baseBarSeries0, 0);
      // Undeclared exception!
      try { 
        dPOIndicator0.calculate(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Size of series: 0 bars, 0 bars removed, index = 0
         //
         verifyException("org.ta4j.core.BaseBarSeries", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      RWIHighIndicator rWIHighIndicator0 = new RWIHighIndicator(baseBarSeries0, 1951);
      rWIHighIndicator0.highestResultIndex = 1951;
      DPOIndicator dPOIndicator0 = new DPOIndicator(rWIHighIndicator0, (-3436));
      // Undeclared exception!
      try { 
        dPOIndicator0.calculate(945);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DPOIndicator dPOIndicator0 = null;
      try {
        dPOIndicator0 = new DPOIndicator((Indicator<Num>) null, 2593);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.CachedIndicator", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      DPOIndicator dPOIndicator0 = new DPOIndicator(baseBarSeries0, Integer.MAX_VALUE);
      String string0 = dPOIndicator0.toString();
      assertEquals("DPOIndicator barCount: 2147483647", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      DPOIndicator dPOIndicator0 = new DPOIndicator(baseBarSeries0, Integer.MAX_VALUE);
      // Undeclared exception!
      try { 
        dPOIndicator0.calculate(Integer.MAX_VALUE);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // List length = -2147483648
         //
         verifyException("java.util.Collections", e);
      }
  }
}
