/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 06 14:22:32 GMT 2021
 */

package org.ta4j.core.indicators.helpers;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.BarSeries;
import org.ta4j.core.indicators.helpers.ClosePriceIndicator;

 
public class ClosePriceIndicator_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClosePriceIndicator closePriceIndicator0 = new ClosePriceIndicator((BarSeries) null);
  }
}
