/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 06 13:59:51 GMT 2021
 */

package org.ta4j.core.indicators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.ta4j.core.BarSeries;
import org.ta4j.core.BaseBarSeries;
import org.ta4j.core.indicators.ATRIndicator;

 
public class ATRIndicator_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ATRIndicator aTRIndicator0 = null;
      try {
        aTRIndicator0 = new ATRIndicator((BarSeries) null, (-2534));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.ta4j.core.indicators.AbstractIndicator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BaseBarSeries baseBarSeries0 = new BaseBarSeries();
      ATRIndicator aTRIndicator0 = null;
      try {
        aTRIndicator0 = new ATRIndicator(baseBarSeries0, (-12));
      
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }
}
